# Generated by Django 5.1 on 2024-08-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='job_posted_date',
            field=models.CharField(max_length=255),
        ),
    ]
