# Generated by Django 5.1 on 2024-08-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_alter_company_company_url_alter_company_job_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_deleted',
            field=models.CharField(max_length=1),
        ),
    ]
