# Generated by Django 5.1 on 2024-08-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_company_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_deleted',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
